//! Opaque handles for recovered C++ classes.
#![allow(non_camel_case_types)]

#[repr(C)]
pub struct AgileGitPtr { _opaque: [u8; 0] }

#[repr(C)]
pub struct AutoStubBias_struct_IUnknown__struct_Windows__Internal__INilDelegate { _opaque: [u8; 0] }

#[repr(C)]
pub struct CMarshaledInterface { _opaque: [u8; 0] }

#[repr(C)]
pub struct CMarshaledInterface_CMarshalStream { _opaque: [u8; 0] }

#[repr(C)]
pub struct Common { _opaque: [u8; 0] }

#[repr(C)]
pub struct Common_DirectoryTreeWalker { _opaque: [u8; 0] }

#[repr(C)]
pub struct Common_StaticLock { _opaque: [u8; 0] }

#[repr(C)]
pub struct ConstrainedImpersonateLoggedOnUser { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_ActivationFactory_class_Microsoft__WRL__Details__Nil__class_Microsoft__WRL__Details__Nil__class_Microsoft__WRL__Details__Nil__0 { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_ActivationFactory_struct_Microsoft__WRL__Implements_class_Microsoft__WRL__FtmBase__struct_Windows__Management__Core__IApplicationDataManagerStatics___struct_Windows__Management__Core__Internal__IApplicationDataManagerStaticsInternal__class_Microsoft__WRL__Details__Nil__0 { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_ActivationFactory_struct_Microsoft__WRL__Implements_class_Microsoft__WRL__FtmBase__struct_Windows__Storage__IApplicationDataStatics___struct_Windows__Storage__IApplicationDataStatics2__class_Microsoft__WRL__Details__Nil__0 { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_AgileRef { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_ComPtr_class_CMarshaledInterface__CMarshalStream { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_ComPtr_class_Microsoft__WRL__Details__EventTargetArray { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_ComPtr_class_Windows__Foundation__Collections__Internal__HashMap_struct_HSTRING_____class_Windows__Storage__ApplicationDataContainer____struct_Windows__Foundation__Collections__Internal__DefaultHash_struct_HSTRING______struct_Windows__Foundation__Collections__Internal__DefaultEqualityPredicate_struct_HSTRING______struct_Windows__Foundation__Collections__Internal__DefaultLifetimeTraits_struct_HSTRING______struct_Windows__Foundation__Collections__Internal__DefaultLifetimeTraits_class_Windows__Storage__ApplicationDataContainer_____struct_Windows__Foundation__Collections__Internal__DefaultHashMapOptions_struct_HSTRING_____class_Windows__Storage__ApplicationDataContainer____struct_Windows__Foundation__Collections__Internal__DefaultLifetimeTraits_struct_HSTRING { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_ComPtr_class_Windows__Foundation__Collections__Internal__HashMap_struct_HSTRING_____struct_IInspectable____struct_Windows__Foundation__Collections__Internal__DefaultHash_struct_HSTRING______struct_Windows__Foundation__Collections__Internal__DefaultEqualityPredicate_struct_HSTRING______struct_Windows__Foundation__Collections__Internal__DefaultLifetimeTraits_struct_HSTRING______struct_Windows__Foundation__Collections__Internal__DefaultLifetimeTraits_struct_IInspectable_____struct_Windows__Foundation__Collections__Internal__HashMapOptions_struct_HSTRING_____struct_IInspectable____struct_Windows__Foundation__Collections__Internal__DefaultLifetimeTraits_struct_HSTRING______1__0__0 { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_ComPtr_class_Windows__Foundation__Collections__Internal__NaiveSplitView_struct_HSTRING_____class_Windows__Storage__ApplicationDataContainer____struct_Windows__Foundation__Collections__Internal__DefaultEqualityPredicate_struct_HSTRING______struct_Windows__Foundation__Collections__Internal__DefaultLifetimeTraits_struct_HSTRING______struct_Windows__Foundation__Collections__Internal__DefaultLifetimeTraits_class_Windows__Storage__ApplicationDataContainer_____struct_Windows__Foundation__Collections__Internal__DefaultHashMapOptions_struct_HSTRING_____class_Windows__Storage__ApplicationDataContainer____struct_Windows__Foundation__Collections__Internal__DefaultLifetimeTraits_struct_HSTRING { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_ComPtr_class_Windows__Foundation__Collections__Internal__NaiveSplitView_struct_HSTRING_____class_Windows__Storage__ApplicationDataContainer____struct_Windows__Foundation__Collections__Internal__DefaultEqualityPredicate_struct_HSTRING______struct_Windows__Foundation__Collections__Internal__DefaultLifetimeTraits_struct_HSTRING______struct_Windows__Foundation__Collections__Internal__DefaultLifetimeTraits_class_Windows__Storage__ApplicationDataContainer_____struct_Windows__Foundation__Collections__Internal__DefaultHashMapOptions_struct_HSTRING_____class_Windows__Storage__ApplicationDataContainer____struct_Windows__Foundation__Collections__Internal__DefaultLifetimeTraits_struct_HSTRING__________Chunk { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_ComPtr_class_Windows__Foundation__Collections__Internal__NaiveSplitView_struct_HSTRING_____struct_IInspectable____struct_Windows__Foundation__Collections__Internal__DefaultEqualityPredicate_struct_HSTRING______struct_Windows__Foundation__Collections__Internal__DefaultLifetimeTraits_struct_HSTRING______struct_Windows__Foundation__Collections__Internal__DefaultLifetimeTraits_struct_IInspectable_____struct_Windows__Foundation__Collections__Internal__HashMapOptions_struct_HSTRING_____struct_IInspectable____struct_Windows__Foundation__Collections__Internal__DefaultLifetimeTraits_struct_HSTRING______1__0__0 { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_ComPtr_class_Windows__Foundation__Collections__Internal__NaiveSplitView_struct_HSTRING_____struct_IInspectable____struct_Windows__Foundation__Collections__Internal__DefaultEqualityPredicate_struct_HSTRING______struct_Windows__Foundation__Collections__Internal__DefaultLifetimeTraits_struct_HSTRING______struct_Windows__Foundation__Collections__Internal__DefaultLifetimeTraits_struct_IInspectable_____struct_Windows__Foundation__Collections__Internal__HashMapOptions_struct_HSTRING_____struct_IInspectable____struct_Windows__Foundation__Collections__Internal__DefaultLifetimeTraits_struct_HSTRING______1__0__0_____Chunk { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_ComPtr_class_Windows__Foundation__Collections__Internal__SimpleKeyValuePair_struct_HSTRING_____class_Windows__Storage__ApplicationDataContainer____struct_Windows__Foundation__Collections__Internal__DefaultLifetimeTraits_struct_HSTRING______struct_Windows__Foundation__Collections__Internal__DefaultLifetimeTraits_class_Windows__Storage__ApplicationDataContainer_____0 { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_ComPtr_class_Windows__Foundation__Collections__Internal__SimpleKeyValuePair_struct_HSTRING_____struct_IInspectable____struct_Windows__Foundation__Collections__Internal__DefaultLifetimeTraits_struct_HSTRING______struct_Windows__Foundation__Collections__Internal__DefaultLifetimeTraits_struct_IInspectable_____0 { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_ComPtr_class_Windows__Storage__ApplicationDataContainerServer { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_ComPtr_class_Windows__Storage__ApplicationDataContainerSettingsServer { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_ComPtr_class_Windows__Storage__StateABIImplementation__ClearOperation { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_ComPtr_class_Windows__Storage__StateABIImplementation__GetForUserOperation { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_ComPtr_class_Windows__Storage__StateABIImplementation__SetVersionOperation { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_ComPtr_struct_IActivationFactory { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_ComPtr_struct_IAgileReference { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_ComPtr_struct_IAsyncInfo { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_ComPtr_struct_IBindCtx { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_ComPtr_struct_IFileSystemBindData2 { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_ComPtr_struct_IGlobalInterfaceTable { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_ComPtr_struct_IInspectable { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_ComPtr_struct_IMarshal { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_ComPtr_struct_IRestrictedErrorInfo { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_ComPtr_struct_IRpcOptions { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_ComPtr_struct_IShellItem { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_ComPtr_struct_IStream { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_ComPtr_struct_IUnknown { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_ComPtr_struct_Windows__ApplicationModel__Core__ICoreApplication { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_ComPtr_struct_Windows__ApplicationModel__Core__ICoreApplicationPrivate { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_ComPtr_struct_Windows__Foundation__Collections__IIterable_struct_Windows__Foundation__Collections__IKeyValuePair_struct_HSTRING_____class_Windows__Storage__ApplicationDataContainer { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_ComPtr_struct_Windows__Foundation__Collections__IIterable_struct_Windows__Foundation__Collections__IKeyValuePair_struct_HSTRING_____struct_IInspectable { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_ComPtr_struct_Windows__Foundation__Collections__IIterator_struct_Windows__Foundation__Collections__IKeyValuePair_struct_HSTRING_____class_Windows__Storage__ApplicationDataContainer { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_ComPtr_struct_Windows__Foundation__Collections__IIterator_struct_Windows__Foundation__Collections__IKeyValuePair_struct_HSTRING_____struct_IInspectable { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_ComPtr_struct_Windows__Foundation__Collections__IKeyValuePair_struct_HSTRING_____class_Windows__Storage__ApplicationDataContainer { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_ComPtr_struct_Windows__Foundation__Collections__IKeyValuePair_struct_HSTRING_____struct_IInspectable { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_ComPtr_struct_Windows__Foundation__Collections__IMapView_struct_HSTRING_____class_Windows__Storage__ApplicationDataContainer { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_ComPtr_struct_Windows__Foundation__Collections__IMapView_struct_HSTRING_____struct_IInspectable { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_ComPtr_struct_Windows__Foundation__Collections__IMap_struct_HSTRING_____struct_IInspectable { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_ComPtr_struct_Windows__Foundation__Collections__IPropertySet { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_ComPtr_struct_Windows__Foundation__Collections__MapChangedEventHandler_struct_HSTRING_____struct_IInspectable { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_ComPtr_struct_Windows__Foundation__IAsyncAction { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_ComPtr_struct_Windows__Foundation__IAsyncActionCompletedHandler { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_ComPtr_struct_Windows__Foundation__IAsyncOperationCompletedHandler_class_Windows__Storage__ApplicationData { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_ComPtr_struct_Windows__Foundation__IAsyncOperation_class_Windows__Storage__ApplicationData { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_ComPtr_struct_Windows__Foundation__IPropertyValueStatics { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_ComPtr_struct_Windows__Foundation__ITypedEventHandler_class_Windows__Storage__ApplicationData____struct_IInspectable { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_ComPtr_struct_Windows__Internal__IAsyncFireCompletion { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_ComPtr_struct_Windows__Internal__INilDelegate { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_ComPtr_struct_Windows__Internal__Storage__IKnownFoldersUserModelStaticsPriv { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_ComPtr_struct_Windows__Management__Deployment__Internal__IPackageManagerStateCreationInternal { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_ComPtr_struct_Windows__Storage__IApplicationData { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_ComPtr_struct_Windows__Storage__IApplicationDataContainer { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_ComPtr_struct_Windows__Storage__IApplicationDataStatics2 { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_ComPtr_struct_Windows__Storage__IKnownFoldersStaticsPriv { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_ComPtr_struct_Windows__Storage__ISetVersionDeferral { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_ComPtr_struct_Windows__Storage__IStorageFolder { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_ComPtr_struct_Windows__Storage__IStorageItem { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_ComPtr_struct_Windows__Storage__Private__IApplicationDataCompositeValueInternal { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_ComPtr_struct_Windows__System__IUser { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_ComPtr_struct_Windows__System__Internal__ISignInStateManager { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_Details { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_Details_ComPtrRef_class_Microsoft_WRL_AgileRef__operator_class_Microsoft_WRL { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_Details_DefaultModule_1 { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_Details_EventTargetArray { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_Details_ImplementsHelper_struct_Microsoft__WRL__RuntimeClassFlags_13___0__struct_IActivationFactory__class_Microsoft__WRL__Details__Nil__class_Microsoft__WRL__Details__Nil__class_Microsoft__WRL__Details__Nil__class_Microsoft__WRL__Details__Nil { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_Details_ImplementsHelper_struct_Microsoft__WRL__RuntimeClassFlags_13___0__struct_IActivationFactory__struct_Microsoft__WRL__Implements_class_Microsoft__WRL__FtmBase__struct_Windows__Management__Core__IApplicationDataManagerStatics___struct_Windows__Management__Core__Internal__IApplicationDataManagerStaticsInternal__class_Microsoft__WRL__Details__Nil__class_Microsoft__WRL__Details__Nil { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_Details_ImplementsHelper_struct_Microsoft__WRL__RuntimeClassFlags_13___0__struct_IActivationFactory__struct_Microsoft__WRL__Implements_class_Microsoft__WRL__FtmBase__struct_Windows__Storage__IApplicationDataStatics___struct_Windows__Storage__IApplicationDataStatics2__class_Microsoft__WRL__Details__Nil__class_Microsoft__WRL__Details__Nil { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_Details_ImplementsHelper_struct_Microsoft__WRL__RuntimeClassFlags_13___1__struct_Microsoft__WRL__Details__ImplementsMarker_struct_Microsoft__WRL__Implements_class_Microsoft__WRL__FtmBase__struct_Windows__Management__Core__IApplicationDataManagerStatics_____struct_Windows__Management__Core__Internal__IApplicationDataManagerStaticsInternal__class_Microsoft__WRL__Details__Nil__class_Microsoft__WRL__Details__Nil { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_Details_ImplementsHelper_struct_Microsoft__WRL__RuntimeClassFlags_13___1__struct_Microsoft__WRL__Details__ImplementsMarker_struct_Microsoft__WRL__Implements_class_Microsoft__WRL__FtmBase__struct_Windows__Storage__IApplicationDataStatics_____struct_Windows__Storage__IApplicationDataStatics2__class_Microsoft__WRL__Details__Nil__class_Microsoft__WRL__Details__Nil { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_Details_ImplementsHelper_struct_Microsoft__WRL__RuntimeClassFlags_1___0__struct_IInspectable__class_Microsoft__WRL__FtmBase__struct_IWeakReferenceSource { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_Details_ImplementsHelper_struct_Microsoft__WRL__RuntimeClassFlags_1___0__struct_Windows__Foundation__Collections__IIterator_struct_Windows__Foundation__Collections__IKeyValuePair_struct_HSTRING_____class_Windows__Storage__ApplicationDataContainer________struct_IWeakReferenceSource { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_Details_ImplementsHelper_struct_Microsoft__WRL__RuntimeClassFlags_1___0__struct_Windows__Foundation__Collections__IIterator_struct_Windows__Foundation__Collections__IKeyValuePair_struct_HSTRING_____struct_IInspectable________struct_IWeakReferenceSource { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_Details_ImplementsHelper_struct_Microsoft__WRL__RuntimeClassFlags_1___0__struct_Windows__Foundation__Collections__IKeyValuePair_struct_HSTRING_____class_Windows__Storage__ApplicationDataContainer_____struct_IWeakReferenceSource { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_Details_ImplementsHelper_struct_Microsoft__WRL__RuntimeClassFlags_1___0__struct_Windows__Foundation__Collections__IKeyValuePair_struct_HSTRING_____struct_IInspectable_____struct_IWeakReferenceSource { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_Details_ImplementsHelper_struct_Microsoft__WRL__RuntimeClassFlags_1___0__struct_Windows__Foundation__Collections__IMapChangedEventArgs_struct_HSTRING______struct_IWeakReferenceSource { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_Details_ImplementsHelper_struct_Microsoft__WRL__RuntimeClassFlags_1___0__struct_Windows__Foundation__Collections__IMapView_struct_HSTRING_____class_Windows__Storage__ApplicationDataContainer_____struct_IWeakReferenceSource__struct_Windows__Foundation__Collections__IIterable_struct_Windows__Foundation__Collections__IKeyValuePair_struct_HSTRING_____class_Windows__Storage__ApplicationDataContainer { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_Details_ImplementsHelper_struct_Microsoft__WRL__RuntimeClassFlags_1___0__struct_Windows__Foundation__Collections__IMapView_struct_HSTRING_____struct_IInspectable_____struct_IWeakReferenceSource__struct_Windows__Foundation__Collections__IIterable_struct_Windows__Foundation__Collections__IKeyValuePair_struct_HSTRING_____struct_IInspectable { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_Details_ImplementsHelper_struct_Microsoft__WRL__RuntimeClassFlags_1___0__struct_Windows__Foundation__Collections__IMap_struct_HSTRING_____class_Windows__Storage__ApplicationDataContainer_____struct_IWeakReferenceSource__struct_Windows__Foundation__Collections__IIterable_struct_Windows__Foundation__Collections__IKeyValuePair_struct_HSTRING_____class_Windows__Storage__ApplicationDataContainer { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_Details_ImplementsHelper_struct_Microsoft__WRL__RuntimeClassFlags_1___0__struct_Windows__Foundation__Collections__IMap_struct_HSTRING_____struct_IInspectable_____struct_IWeakReferenceSource__struct_Windows__Foundation__Collections__IIterable_struct_Windows__Foundation__Collections__IKeyValuePair_struct_HSTRING_____struct_IInspectable________struct_Windows__Foundation__Collections__IObservableMap_struct_HSTRING_____struct_IInspectable { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_Details_ImplementsHelper_struct_Microsoft__WRL__RuntimeClassFlags_1___0__struct_Windows__Storage__ISetVersionDeferral__struct_IWeakReferenceSource__class_Microsoft__WRL__FtmBase { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_Details_ImplementsHelper_struct_Microsoft__WRL__RuntimeClassFlags_1___0__struct_Windows__Storage__ISetVersionRequest__struct_IWeakReferenceSource__class_Microsoft__WRL__FtmBase { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_Details_ImplementsHelper_struct_Microsoft__WRL__RuntimeClassFlags_1___1__struct_IWeakReferenceSource { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_Details_ImplementsHelper_struct_Microsoft__WRL__RuntimeClassFlags_1___1__struct_IWeakReferenceSource__class_Microsoft__WRL__FtmBase { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_Details_ImplementsHelper_struct_Microsoft__WRL__RuntimeClassFlags_1___1__struct_IWeakReferenceSource__struct_Windows__Foundation__Collections__IIterable_struct_Windows__Foundation__Collections__IKeyValuePair_struct_HSTRING_____class_Windows__Storage__ApplicationDataContainer { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_Details_ImplementsHelper_struct_Microsoft__WRL__RuntimeClassFlags_1___1__struct_IWeakReferenceSource__struct_Windows__Foundation__Collections__IIterable_struct_Windows__Foundation__Collections__IKeyValuePair_struct_HSTRING_____struct_IInspectable { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_Details_ImplementsHelper_struct_Microsoft__WRL__RuntimeClassFlags_1___1__struct_IWeakReferenceSource__struct_Windows__Foundation__Collections__IIterable_struct_Windows__Foundation__Collections__IKeyValuePair_struct_HSTRING_____struct_IInspectable________struct_Windows__Foundation__Collections__IObservableMap_struct_HSTRING_____struct_IInspectable { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_Details_ImplementsHelper_struct_Microsoft__WRL__RuntimeClassFlags_1___1__struct_IWeakReferenceSource__struct_Windows__Foundation__IClosable__class_Microsoft__WRL__FtmBase { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_Details_ImplementsHelper_struct_Microsoft__WRL__RuntimeClassFlags_1___1__struct_Microsoft__WRL__Details__ImplementsMarker_class_Microsoft__WRL__FtmBase { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_Details_ImplementsHelper_struct_Microsoft__WRL__RuntimeClassFlags_1___1__struct_Microsoft__WRL__Details__ImplementsMarker_class_Microsoft__WRL__FtmBase___struct_IWeakReferenceSource { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_Details_ImplementsHelper_struct_Microsoft__WRL__RuntimeClassFlags_1___1__struct_Microsoft__WRL__Details__ImplementsMarker_class_Microsoft__WRL__FtmBase___struct_Windows__Management__Core__IApplicationDataManagerStatics { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_Details_ImplementsHelper_struct_Microsoft__WRL__RuntimeClassFlags_1___1__struct_Microsoft__WRL__Details__ImplementsMarker_class_Microsoft__WRL__FtmBase___struct_Windows__Storage__IApplicationDataStatics { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_Details_ImplementsHelper_struct_Microsoft__WRL__RuntimeClassFlags_1___1__struct_Windows__Foundation__Collections__IIterable_struct_Windows__Foundation__Collections__IKeyValuePair_struct_HSTRING_____class_Windows__Storage__ApplicationDataContainer { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_Details_ImplementsHelper_struct_Microsoft__WRL__RuntimeClassFlags_1___1__struct_Windows__Foundation__Collections__IIterable_struct_Windows__Foundation__Collections__IKeyValuePair_struct_HSTRING_____struct_IInspectable { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_Details_ImplementsHelper_struct_Microsoft__WRL__RuntimeClassFlags_1___1__struct_Windows__Foundation__Collections__IIterable_struct_Windows__Foundation__Collections__IKeyValuePair_struct_HSTRING_____struct_IInspectable________struct_Windows__Foundation__Collections__IObservableMap_struct_HSTRING_____struct_IInspectable { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_Details_ImplementsHelper_struct_Microsoft__WRL__RuntimeClassFlags_1___1__struct_Windows__Foundation__Collections__IObservableMap_struct_HSTRING_____struct_IInspectable { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_Details_ImplementsHelper_struct_Microsoft__WRL__RuntimeClassFlags_1___1__struct_Windows__Foundation__Collections__IObservableMap_struct_HSTRING_____struct_IInspectable_____struct_Windows__Foundation__Collections__IPropertySet__class_Microsoft__WRL__FtmBase { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_Details_ImplementsHelper_struct_Microsoft__WRL__RuntimeClassFlags_1___1__struct_Windows__Foundation__Collections__IPropertySet__class_Microsoft__WRL__FtmBase { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_Details_ImplementsHelper_struct_Microsoft__WRL__RuntimeClassFlags_1___1__struct_Windows__Foundation__Collections__IPropertySet__struct_Windows__Storage__Private__IApplicationDataCompositeValueInternal__class_Microsoft__WRL__FtmBase { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_Details_ImplementsHelper_struct_Microsoft__WRL__RuntimeClassFlags_1___1__struct_Windows__Foundation__IClosable__class_Microsoft__WRL__FtmBase { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_Details_ImplementsHelper_struct_Microsoft__WRL__RuntimeClassFlags_1___1__struct_Windows__Storage__IApplicationData2__struct_Windows__Storage__IApplicationData3__struct_Windows__Foundation__IClosable__class_Microsoft__WRL__FtmBase { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_Details_ImplementsHelper_struct_Microsoft__WRL__RuntimeClassFlags_1___1__struct_Windows__Storage__IApplicationData3__struct_Windows__Foundation__IClosable__class_Microsoft__WRL__FtmBase { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_Details_ImplementsHelper_struct_Microsoft__WRL__RuntimeClassFlags_1___1__struct_Windows__Storage__Private__IApplicationDataCompositeValueInternal__class_Microsoft__WRL__FtmBase { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_Details_ImplementsHelper_struct_Microsoft__WRL__RuntimeClassFlags_3___1__struct_IWeakReferenceSource__struct_Windows__Foundation__IAsyncOperation_class_Windows__Storage__ApplicationData_____struct_Windows__Internal__IAsyncOperationLocal__struct_Microsoft__WRL__CloakedIid_struct_Windows__Internal__IAsyncDeferral___struct_Microsoft__WRL__CloakedIid_struct_Windows__Internal__IComPoolTask___struct_Microsoft__WRL__CloakedIid_struct_Windows__Internal__IAsyncFireCompletion { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_Details_ImplementsHelper_struct_Microsoft__WRL__RuntimeClassFlags_3___1__struct_Windows__Foundation__IAsyncOperation_class_Windows__Storage__ApplicationData_____struct_Windows__Internal__IAsyncOperationLocal__struct_Microsoft__WRL__CloakedIid_struct_Windows__Internal__IAsyncDeferral___struct_Microsoft__WRL__CloakedIid_struct_Windows__Internal__IComPoolTask___struct_Microsoft__WRL__CloakedIid_struct_Windows__Internal__IAsyncFireCompletion { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_Details_ImplementsHelper_struct_Microsoft__WRL__RuntimeClassFlags_3___1__struct_Windows__Internal__IAsyncOperationLocal__struct_Microsoft__WRL__CloakedIid_struct_Windows__Internal__IAsyncDeferral___struct_Microsoft__WRL__CloakedIid_struct_Windows__Internal__IComPoolTask___struct_Microsoft__WRL__CloakedIid_struct_Windows__Internal__IAsyncFireCompletion { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_Details_MakeAllocator_class_CMarshaledInterface__CMarshalStream { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_Details_MakeAllocator_class_Microsoft__WRL__Details__EventTargetArray { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_Details_MakeAllocator_class_Microsoft__WRL__SimpleSealedActivationFactory_class_Windows__Storage__ApplicationDataCompositeValueServer__0 { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_Details_MakeAllocator_class_Windows__Foundation__Collections__Internal__NaiveSplitView_struct_HSTRING_____class_Windows__Storage__ApplicationDataContainer____struct_Windows__Foundation__Collections__Internal__DefaultEqualityPredicate_struct_HSTRING______struct_Windows__Foundation__Collections__Internal__DefaultLifetimeTraits_struct_HSTRING______struct_Windows__Foundation__Collections__Internal__DefaultLifetimeTraits_class_Windows__Storage__ApplicationDataContainer_____struct_Windows__Foundation__Collections__Internal__DefaultHashMapOptions_struct_HSTRING_____class_Windows__Storage__ApplicationDataContainer____struct_Windows__Foundation__Collections__Internal__DefaultLifetimeTraits_struct_HSTRING { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_Details_MakeAllocator_class_Windows__Foundation__Collections__Internal__NaiveSplitView_struct_HSTRING_____class_Windows__Storage__ApplicationDataContainer____struct_Windows__Foundation__Collections__Internal__DefaultEqualityPredicate_struct_HSTRING______struct_Windows__Foundation__Collections__Internal__DefaultLifetimeTraits_struct_HSTRING______struct_Windows__Foundation__Collections__Internal__DefaultLifetimeTraits_class_Windows__Storage__ApplicationDataContainer_____struct_Windows__Foundation__Collections__Internal__DefaultHashMapOptions_struct_HSTRING_____class_Windows__Storage__ApplicationDataContainer____struct_Windows__Foundation__Collections__Internal__DefaultLifetimeTraits_struct_HSTRING__________ChunkElementIterator { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_Details_MakeAllocator_class_Windows__Foundation__Collections__Internal__NaiveSplitView_struct_HSTRING_____class_Windows__Storage__ApplicationDataContainer____struct_Windows__Foundation__Collections__Internal__DefaultEqualityPredicate_struct_HSTRING______struct_Windows__Foundation__Collections__Internal__DefaultLifetimeTraits_struct_HSTRING______struct_Windows__Foundation__Collections__Internal__DefaultLifetimeTraits_class_Windows__Storage__ApplicationDataContainer_____struct_Windows__Foundation__Collections__Internal__DefaultHashMapOptions_struct_HSTRING_____class_Windows__Storage__ApplicationDataContainer____struct_Windows__Foundation__Collections__Internal__DefaultLifetimeTraits_struct_HSTRING__________ChunkView { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_Details_MakeAllocator_class_Windows__Foundation__Collections__Internal__NaiveSplitView_struct_HSTRING_____class_Windows__Storage__ApplicationDataContainer____struct_Windows__Foundation__Collections__Internal__DefaultEqualityPredicate_struct_HSTRING______struct_Windows__Foundation__Collections__Internal__DefaultLifetimeTraits_struct_HSTRING______struct_Windows__Foundation__Collections__Internal__DefaultLifetimeTraits_class_Windows__Storage__ApplicationDataContainer_____struct_Windows__Foundation__Collections__Internal__DefaultHashMapOptions_struct_HSTRING_____class_Windows__Storage__ApplicationDataContainer____struct_Windows__Foundation__Collections__Internal__DefaultLifetimeTraits_struct_HSTRING__________SplitIterator { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_Details_MakeAllocator_class_Windows__Foundation__Collections__Internal__NaiveSplitView_struct_HSTRING_____struct_IInspectable____struct_Windows__Foundation__Collections__Internal__DefaultEqualityPredicate_struct_HSTRING______struct_Windows__Foundation__Collections__Internal__DefaultLifetimeTraits_struct_HSTRING______struct_Windows__Foundation__Collections__Internal__DefaultLifetimeTraits_struct_IInspectable_____struct_Windows__Foundation__Collections__Internal__HashMapOptions_struct_HSTRING_____struct_IInspectable____struct_Windows__Foundation__Collections__Internal__DefaultLifetimeTraits_struct_HSTRING______1__0__0 { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_Details_MakeAllocator_class_Windows__Foundation__Collections__Internal__NaiveSplitView_struct_HSTRING_____struct_IInspectable____struct_Windows__Foundation__Collections__Internal__DefaultEqualityPredicate_struct_HSTRING______struct_Windows__Foundation__Collections__Internal__DefaultLifetimeTraits_struct_HSTRING______struct_Windows__Foundation__Collections__Internal__DefaultLifetimeTraits_struct_IInspectable_____struct_Windows__Foundation__Collections__Internal__HashMapOptions_struct_HSTRING_____struct_IInspectable____struct_Windows__Foundation__Collections__Internal__DefaultLifetimeTraits_struct_HSTRING______1__0__0_____ChunkElementIterator { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_Details_MakeAllocator_class_Windows__Foundation__Collections__Internal__NaiveSplitView_struct_HSTRING_____struct_IInspectable____struct_Windows__Foundation__Collections__Internal__DefaultEqualityPredicate_struct_HSTRING______struct_Windows__Foundation__Collections__Internal__DefaultLifetimeTraits_struct_HSTRING______struct_Windows__Foundation__Collections__Internal__DefaultLifetimeTraits_struct_IInspectable_____struct_Windows__Foundation__Collections__Internal__HashMapOptions_struct_HSTRING_____struct_IInspectable____struct_Windows__Foundation__Collections__Internal__DefaultLifetimeTraits_struct_HSTRING______1__0__0_____ChunkView { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_Details_MakeAllocator_class_Windows__Foundation__Collections__Internal__NaiveSplitView_struct_HSTRING_____struct_IInspectable____struct_Windows__Foundation__Collections__Internal__DefaultEqualityPredicate_struct_HSTRING______struct_Windows__Foundation__Collections__Internal__DefaultLifetimeTraits_struct_HSTRING______struct_Windows__Foundation__Collections__Internal__DefaultLifetimeTraits_struct_IInspectable_____struct_Windows__Foundation__Collections__Internal__HashMapOptions_struct_HSTRING_____struct_IInspectable____struct_Windows__Foundation__Collections__Internal__DefaultLifetimeTraits_struct_HSTRING______1__0__0_____SplitIterator { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_Details_MakeAllocator_class_Windows__Internal__ComTaskPool__CTaskWrapper_class__lambda_c2fd7731c5ae0d37e65ea73be67c0f1b { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_Details_MakeAllocator_class_Windows__Management__Core__ApplicationDataManagerFactoryServer { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_Details_MakeAllocator_class_Windows__Storage__ApplicationDataCompositeValueServer { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_Details_MakeAllocator_class_Windows__Storage__ApplicationDataFactoryServer { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_Details_MakeAllocator_class_Windows__Storage__RestrictedApplicationDataServer { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_Details_MakeAllocator_class_Windows__Storage__SetVersionDeferral { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_Details_MakeAllocator_class_Windows__Storage__SetVersionRequest { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_Details_MakeAllocator_class_Windows__Storage__StateABIImplementation__ClearOperation { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_Details_MakeAllocator_class_Windows__Storage__StateABIImplementation__GetForUserOperation { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_Details_MakeAllocator_class_Windows__Storage__StateABIImplementation__SetVersionOperation { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_Details_MakeAllocator_struct_Windows__Internal__Details__GitInvokeHelper_struct_Windows__Foundation__Collections__MapChangedEventHandler_struct_HSTRING_____struct_IInspectable_____class_Windows__Internal__GitPtr__2 { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_Details_ModuleBase { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_Details_RuntimeClassBaseT_1 { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_Details_RuntimeClassBaseT_13 { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_Details_RuntimeClassBaseT_2 { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_Details_RuntimeClassImpl_struct_Microsoft__WRL__RuntimeClassFlags_13___0__1__0__struct_IActivationFactory__class_Microsoft__WRL__Details__Nil__class_Microsoft__WRL__Details__Nil__class_Microsoft__WRL__Details__Nil__class_Microsoft__WRL__Details__Nil { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_Details_RuntimeClassImpl_struct_Microsoft__WRL__RuntimeClassFlags_13___0__1__0__struct_IActivationFactory__struct_Microsoft__WRL__Implements_class_Microsoft__WRL__FtmBase__struct_Windows__Management__Core__IApplicationDataManagerStatics___struct_Windows__Management__Core__Internal__IApplicationDataManagerStaticsInternal__class_Microsoft__WRL__Details__Nil__class_Microsoft__WRL__Details__Nil { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_Details_RuntimeClassImpl_struct_Microsoft__WRL__RuntimeClassFlags_13___0__1__0__struct_IActivationFactory__struct_Microsoft__WRL__Implements_class_Microsoft__WRL__FtmBase__struct_Windows__Storage__IApplicationDataStatics___struct_Windows__Storage__IApplicationDataStatics2__class_Microsoft__WRL__Details__Nil__class_Microsoft__WRL__Details__Nil { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_Details_RuntimeClassImpl_struct_Microsoft__WRL__RuntimeClassFlags_1___1__1__0__class_Microsoft__WRL__FtmBase { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_Details_RuntimeClassImpl_struct_Microsoft__WRL__RuntimeClassFlags_1___1__1__0__struct_Windows__Foundation__Collections__IIterator_struct_Windows__Foundation__Collections__IKeyValuePair_struct_HSTRING_____class_Windows__Storage__ApplicationDataContainer { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_Details_RuntimeClassImpl_struct_Microsoft__WRL__RuntimeClassFlags_1___1__1__0__struct_Windows__Foundation__Collections__IIterator_struct_Windows__Foundation__Collections__IKeyValuePair_struct_HSTRING_____struct_IInspectable { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_Details_RuntimeClassImpl_struct_Microsoft__WRL__RuntimeClassFlags_1___1__1__0__struct_Windows__Foundation__Collections__IKeyValuePair_struct_HSTRING_____class_Windows__Storage__ApplicationDataContainer { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_Details_RuntimeClassImpl_struct_Microsoft__WRL__RuntimeClassFlags_1___1__1__0__struct_Windows__Foundation__Collections__IKeyValuePair_struct_HSTRING_____struct_IInspectable { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_Details_RuntimeClassImpl_struct_Microsoft__WRL__RuntimeClassFlags_1___1__1__0__struct_Windows__Foundation__Collections__IMapChangedEventArgs_struct_HSTRING { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_Details_RuntimeClassImpl_struct_Microsoft__WRL__RuntimeClassFlags_1___1__1__0__struct_Windows__Foundation__Collections__IMapView_struct_HSTRING_____class_Windows__Storage__ApplicationDataContainer_____struct_Windows__Foundation__Collections__IIterable_struct_Windows__Foundation__Collections__IKeyValuePair_struct_HSTRING_____class_Windows__Storage__ApplicationDataContainer { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_Details_RuntimeClassImpl_struct_Microsoft__WRL__RuntimeClassFlags_1___1__1__0__struct_Windows__Foundation__Collections__IMapView_struct_HSTRING_____struct_IInspectable_____struct_Windows__Foundation__Collections__IIterable_struct_Windows__Foundation__Collections__IKeyValuePair_struct_HSTRING_____struct_IInspectable { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_Details_RuntimeClassImpl_struct_Microsoft__WRL__RuntimeClassFlags_1___1__1__0__struct_Windows__Foundation__Collections__IMap_struct_HSTRING_____class_Windows__Storage__ApplicationDataContainer_____struct_Windows__Foundation__Collections__IIterable_struct_Windows__Foundation__Collections__IKeyValuePair_struct_HSTRING_____class_Windows__Storage__ApplicationDataContainer { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_Details_RuntimeClassImpl_struct_Microsoft__WRL__RuntimeClassFlags_1___1__1__0__struct_Windows__Foundation__Collections__IMap_struct_HSTRING_____struct_IInspectable_____struct_Windows__Foundation__Collections__IIterable_struct_Windows__Foundation__Collections__IKeyValuePair_struct_HSTRING_____struct_IInspectable________struct_Windows__Foundation__Collections__IObservableMap_struct_HSTRING_____struct_IInspectable { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_Details_RuntimeClassImpl_struct_Microsoft__WRL__RuntimeClassFlags_1___1__1__0__struct_Windows__Foundation__Collections__IMap_struct_HSTRING_____struct_IInspectable_____struct_Windows__Foundation__Collections__IIterable_struct_Windows__Foundation__Collections__IKeyValuePair_struct_HSTRING_____struct_IInspectable________struct_Windows__Foundation__Collections__IObservableMap_struct_HSTRING_____struct_IInspectable_____struct_Windows__Foundation__Collections__IPropertySet__class_Microsoft__WRL__FtmBase { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_Details_RuntimeClassImpl_struct_Microsoft__WRL__RuntimeClassFlags_1___1__1__0__struct_Windows__Foundation__Collections__IMap_struct_HSTRING_____struct_IInspectable_____struct_Windows__Foundation__Collections__IIterable_struct_Windows__Foundation__Collections__IKeyValuePair_struct_HSTRING_____struct_IInspectable________struct_Windows__Foundation__Collections__IObservableMap_struct_HSTRING_____struct_IInspectable_____struct_Windows__Foundation__Collections__IPropertySet__struct_Windows__Storage__Private__IApplicationDataCompositeValueInternal__class_Microsoft__WRL__FtmBase { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_Details_RuntimeClassImpl_struct_Microsoft__WRL__RuntimeClassFlags_1___1__1__0__struct_Windows__Storage__IApplicationDataContainer__struct_Windows__Foundation__IClosable__class_Microsoft__WRL__FtmBase { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_Details_RuntimeClassImpl_struct_Microsoft__WRL__RuntimeClassFlags_1___1__1__0__struct_Windows__Storage__IApplicationData__struct_Windows__Storage__IApplicationData2__struct_Windows__Storage__IApplicationData3__struct_Windows__Foundation__IClosable__class_Microsoft__WRL__FtmBase { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_Details_RuntimeClassImpl_struct_Microsoft__WRL__RuntimeClassFlags_1___1__1__0__struct_Windows__Storage__ISetVersionDeferral__class_Microsoft__WRL__FtmBase { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_Details_RuntimeClassImpl_struct_Microsoft__WRL__RuntimeClassFlags_1___1__1__0__struct_Windows__Storage__ISetVersionRequest__class_Microsoft__WRL__FtmBase { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_Details_RuntimeClassImpl_struct_Microsoft__WRL__RuntimeClassFlags_2___1__0__0__struct_IFileSystemBindData__struct_IFileSystemBindData2 { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_Details_RuntimeClassImpl_struct_Microsoft__WRL__RuntimeClassFlags_2___1__0__0__struct_IUnknown { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_Details_RuntimeClassImpl_struct_Microsoft__WRL__RuntimeClassFlags_2___1__0__0__struct_IWeakReference { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_Details_RuntimeClassImpl_struct_Microsoft__WRL__RuntimeClassFlags_2___1__0__0__struct_Windows__Foundation__Collections__MapChangedEventHandler_struct_HSTRING_____struct_IInspectable_____class_Microsoft__WRL__FtmBase { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_Details_RuntimeClassImpl_struct_Microsoft__WRL__RuntimeClassFlags_2___1__0__0__struct_Windows__Foundation__ITypedEventHandler_class_Windows__Storage__ApplicationData____struct_IInspectable_____class_Microsoft__WRL__FtmBase { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_Details_RuntimeClassImpl_struct_Microsoft__WRL__RuntimeClassFlags_2___1__0__0__struct_Windows__Internal__IComPoolTask { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_Details_RuntimeClass_struct_Microsoft__WRL__Details__InterfaceListHelper_struct_IActivationFactory__class_Microsoft__WRL__Details__Nil__class_Microsoft__WRL__Details__Nil__class_Microsoft__WRL__Details__Nil__class_Microsoft__WRL__Details__Nil___struct_Microsoft__WRL__RuntimeClassFlags_13___0__1__0 { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_Details_RuntimeClass_struct_Microsoft__WRL__Details__InterfaceListHelper_struct_IActivationFactory__struct_Microsoft__WRL__Implements_class_Microsoft__WRL__FtmBase__struct_Windows__Management__Core__IApplicationDataManagerStatics___struct_Windows__Management__Core__Internal__IApplicationDataManagerStaticsInternal__class_Microsoft__WRL__Details__Nil__class_Microsoft__WRL__Details__Nil___struct_Microsoft__WRL__RuntimeClassFlags_13___0__1__0 { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_Details_RuntimeClass_struct_Microsoft__WRL__Details__InterfaceListHelper_struct_IActivationFactory__struct_Microsoft__WRL__Implements_class_Microsoft__WRL__FtmBase__struct_Windows__Storage__IApplicationDataStatics___struct_Windows__Storage__IApplicationDataStatics2__class_Microsoft__WRL__Details__Nil__class_Microsoft__WRL__Details__Nil___struct_Microsoft__WRL__RuntimeClassFlags_13___0__1__0 { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_Details_StaticStorage_class_Microsoft__WRL__Details__DefaultModule_1___0__int { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_Details_WeakReferenceImpl { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_ErrorPropagationPolicyTraits__1 { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_EventSource_struct_Windows__Foundation__Collections__MapChangedEventHandler_struct_HSTRING_____struct_IInspectable_____struct_Microsoft__WRL__InvokeModeOptions__2 { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_EventSource_struct_Windows__Foundation__ITypedEventHandler_class_Windows__Storage__ApplicationData____struct_IInspectable_____struct_Microsoft__WRL__InvokeModeOptions__2 { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_FtmBase { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_Implements_class_Microsoft__WRL__FtmBase__struct_Windows__Management__Core__IApplicationDataManagerStatics { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_Implements_class_Microsoft__WRL__FtmBase__struct_Windows__Storage__IApplicationDataStatics { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_InvokeTraits__2 { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_Module_1__class_Microsoft__WRL__Details__DefaultModule_1 { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_RuntimeClass_class_Microsoft__WRL__FtmBase { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_RuntimeClass_struct_Microsoft__WRL__RuntimeClassFlags_2___struct_IFileSystemBindData__struct_IFileSystemBindData2 { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_RuntimeClass_struct_Microsoft__WRL__RuntimeClassFlags_2___struct_IUnknown { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_RuntimeClass_struct_Microsoft__WRL__RuntimeClassFlags_2___struct_IWeakReference { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_RuntimeClass_struct_Microsoft__WRL__RuntimeClassFlags_2___struct_Windows__Foundation__Collections__MapChangedEventHandler_struct_HSTRING_____struct_IInspectable_____class_Microsoft__WRL__FtmBase { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_RuntimeClass_struct_Microsoft__WRL__RuntimeClassFlags_2___struct_Windows__Foundation__ITypedEventHandler_class_Windows__Storage__ApplicationData____struct_IInspectable_____class_Microsoft__WRL__FtmBase { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_RuntimeClass_struct_Microsoft__WRL__RuntimeClassFlags_2___struct_Windows__Internal__IComPoolTask { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_RuntimeClass_struct_Windows__Foundation__Collections__IIterator_struct_Windows__Foundation__Collections__IKeyValuePair_struct_HSTRING_____class_Windows__Storage__ApplicationDataContainer { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_RuntimeClass_struct_Windows__Foundation__Collections__IIterator_struct_Windows__Foundation__Collections__IKeyValuePair_struct_HSTRING_____struct_IInspectable { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_RuntimeClass_struct_Windows__Foundation__Collections__IKeyValuePair_struct_HSTRING_____class_Windows__Storage__ApplicationDataContainer { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_RuntimeClass_struct_Windows__Foundation__Collections__IKeyValuePair_struct_HSTRING_____struct_IInspectable { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_RuntimeClass_struct_Windows__Foundation__Collections__IMapChangedEventArgs_struct_HSTRING { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_RuntimeClass_struct_Windows__Foundation__Collections__IMapView_struct_HSTRING_____class_Windows__Storage__ApplicationDataContainer_____struct_Windows__Foundation__Collections__IIterable_struct_Windows__Foundation__Collections__IKeyValuePair_struct_HSTRING_____class_Windows__Storage__ApplicationDataContainer { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_RuntimeClass_struct_Windows__Foundation__Collections__IMapView_struct_HSTRING_____struct_IInspectable_____struct_Windows__Foundation__Collections__IIterable_struct_Windows__Foundation__Collections__IKeyValuePair_struct_HSTRING_____struct_IInspectable { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_RuntimeClass_struct_Windows__Foundation__Collections__IMap_struct_HSTRING_____class_Windows__Storage__ApplicationDataContainer_____struct_Windows__Foundation__Collections__IIterable_struct_Windows__Foundation__Collections__IKeyValuePair_struct_HSTRING_____class_Windows__Storage__ApplicationDataContainer { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_RuntimeClass_struct_Windows__Foundation__Collections__IMap_struct_HSTRING_____struct_IInspectable_____struct_Windows__Foundation__Collections__IIterable_struct_Windows__Foundation__Collections__IKeyValuePair_struct_HSTRING_____struct_IInspectable________struct_Windows__Foundation__Collections__IObservableMap_struct_HSTRING_____struct_IInspectable { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_RuntimeClass_struct_Windows__Foundation__Collections__IMap_struct_HSTRING_____struct_IInspectable_____struct_Windows__Foundation__Collections__IIterable_struct_Windows__Foundation__Collections__IKeyValuePair_struct_HSTRING_____struct_IInspectable________struct_Windows__Foundation__Collections__IObservableMap_struct_HSTRING_____struct_IInspectable_____struct_Windows__Foundation__Collections__IPropertySet__class_Microsoft__WRL__FtmBase { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_RuntimeClass_struct_Windows__Foundation__Collections__IMap_struct_HSTRING_____struct_IInspectable_____struct_Windows__Foundation__Collections__IIterable_struct_Windows__Foundation__Collections__IKeyValuePair_struct_HSTRING_____struct_IInspectable________struct_Windows__Foundation__Collections__IObservableMap_struct_HSTRING_____struct_IInspectable_____struct_Windows__Foundation__Collections__IPropertySet__struct_Windows__Storage__Private__IApplicationDataCompositeValueInternal__class_Microsoft__WRL__FtmBase { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_RuntimeClass_struct_Windows__Storage__IApplicationDataContainer__struct_Windows__Foundation__IClosable__class_Microsoft__WRL__FtmBase { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_RuntimeClass_struct_Windows__Storage__IApplicationData__struct_Windows__Storage__IApplicationData2__struct_Windows__Storage__IApplicationData3__struct_Windows__Foundation__IClosable__class_Microsoft__WRL__FtmBase { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_RuntimeClass_struct_Windows__Storage__ISetVersionDeferral__class_Microsoft__WRL__FtmBase { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_RuntimeClass_struct_Windows__Storage__ISetVersionRequest__class_Microsoft__WRL__FtmBase { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_SimpleActivationFactory_class_Windows__Storage__ApplicationDataCompositeValueServer__0 { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_SimpleSealedActivationFactory_class_Windows__Storage__ApplicationDataCompositeValueServer__0 { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_Wrappers_HStringReference { _opaque: [u8; 0] }

#[repr(C)]
pub struct Microsoft_WRL_Wrappers_SRWLock { _opaque: [u8; 0] }

#[repr(C)]
pub struct RoVariant { _opaque: [u8; 0] }

#[repr(C)]
pub struct RoVariant_Accessor { _opaque: [u8; 0] }

#[repr(C)]
pub struct RpcOptionsHelper { _opaque: [u8; 0] }

#[repr(C)]
pub struct State { _opaque: [u8; 0] }

#[repr(C)]
pub struct StateSchema { _opaque: [u8; 0] }

#[repr(C)]
pub struct State_AutoReleaseStateLock { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Foundation { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Foundation_Collections_Detail { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Foundation_Collections_IIterable_impl_struct_Windows__Foundation__Collections__IKeyValuePair_struct_HSTRING_____class_Windows__Storage__ApplicationDataContainer { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Foundation_Collections_IIterable_impl_struct_Windows__Foundation__Collections__IKeyValuePair_struct_HSTRING_____struct_IInspectable { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Foundation_Collections_IIterable_struct_Windows__Foundation__Collections__IKeyValuePair_struct_HSTRING_____class_Windows__Storage__ApplicationDataContainer { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Foundation_Collections_IIterable_struct_Windows__Foundation__Collections__IKeyValuePair_struct_HSTRING_____struct_IInspectable { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Foundation_Collections_IIterator_impl_struct_Windows__Foundation__Collections__IKeyValuePair_struct_HSTRING_____class_Windows__Storage__ApplicationDataContainer_______1 { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Foundation_Collections_IIterator_impl_struct_Windows__Foundation__Collections__IKeyValuePair_struct_HSTRING_____struct_IInspectable_______1 { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Foundation_Collections_IIterator_struct_Windows__Foundation__Collections__IKeyValuePair_struct_HSTRING_____class_Windows__Storage__ApplicationDataContainer { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Foundation_Collections_IIterator_struct_Windows__Foundation__Collections__IKeyValuePair_struct_HSTRING_____struct_IInspectable { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Foundation_Collections_IKeyValuePair_impl_struct_HSTRING_____struct_IInspectable { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Foundation_Collections_IKeyValuePair_impl_struct_HSTRING_____struct_Windows__Foundation__Internal__AggregateType_class_Windows__Storage__ApplicationDataContainer____struct_Windows__Storage__IApplicationDataContainer { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Foundation_Collections_IKeyValuePair_struct_HSTRING_____class_Windows__Storage__ApplicationDataContainer { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Foundation_Collections_IKeyValuePair_struct_HSTRING_____struct_IInspectable { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Foundation_Collections_IMapChangedEventArgs_impl_struct_HSTRING { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Foundation_Collections_IMapChangedEventArgs_struct_HSTRING { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Foundation_Collections_IMapView_impl_struct_HSTRING_____struct_IInspectable { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Foundation_Collections_IMapView_impl_struct_HSTRING_____struct_Windows__Foundation__Internal__AggregateType_class_Windows__Storage__ApplicationDataContainer____struct_Windows__Storage__IApplicationDataContainer { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Foundation_Collections_IMapView_struct_HSTRING_____class_Windows__Storage__ApplicationDataContainer { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Foundation_Collections_IMapView_struct_HSTRING_____struct_IInspectable { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Foundation_Collections_IMap_impl_struct_HSTRING_____struct_IInspectable { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Foundation_Collections_IMap_impl_struct_HSTRING_____struct_Windows__Foundation__Internal__AggregateType_class_Windows__Storage__ApplicationDataContainer____struct_Windows__Storage__IApplicationDataContainer { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Foundation_Collections_IMap_struct_HSTRING_____class_Windows__Storage__ApplicationDataContainer { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Foundation_Collections_IMap_struct_HSTRING_____struct_IInspectable { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Foundation_Collections_IObservableMap_impl_struct_HSTRING_____struct_IInspectable { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Foundation_Collections_IObservableMap_struct_HSTRING_____struct_IInspectable { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Foundation_Collections_Internal_HashMapOptions_struct_HSTRING_____class_Windows__Storage__ApplicationDataContainer____struct_Windows__Foundation__Collections__Internal__DefaultLifetimeTraits_struct_HSTRING______0__0__0 { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Foundation_Collections_Internal_HashMapOptions_struct_HSTRING_____struct_IInspectable____struct_Windows__Foundation__Collections__Internal__DefaultLifetimeTraits_struct_HSTRING______1__0__0 { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Foundation_Collections_Internal_HashMap_struct_HSTRING_____class_Windows_Storage_ApplicationDataContainer____struct_Windows_Foundation_Collections_Internal_DefaultHash_struct_HSTRING______struct_Windows_Foundation_Collections_Internal_DefaultEqualityPredicate_struct_HSTRING______struct_Windows_Foundation_Collections_Internal_DefaultLifetimeTraits_struct_HSTRING______struct_Windows_Foundation_Collections_Internal_DefaultLifetimeTraits_class_Windows_Storage_ApplicationDataContainer_____struct_Windows_Foundation_Collections_Internal_DefaultHashMapOptions_struct_HSTRING_____class_Windows_Storage_ApplicationDataContainer____struct_Windows_Foundation_Collections_Internal_DefaultLifetimeTraits_struct_HSTRING_________Iterator { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Foundation_Collections_Internal_HashMap_struct_HSTRING_____class_Windows_Storage_ApplicationDataContainer____struct_Windows_Foundation_Collections_Internal_DefaultHash_struct_HSTRING______struct_Windows_Foundation_Collections_Internal_DefaultEqualityPredicate_struct_HSTRING______struct_Windows_Foundation_Collections_Internal_DefaultLifetimeTraits_struct_HSTRING______struct_Windows_Foundation_Collections_Internal_DefaultLifetimeTraits_class_Windows_Storage_ApplicationDataContainer_____struct_Windows_Foundation_Collections_Internal_DefaultHashMapOptions_struct_HSTRING_____class_Windows_Storage_ApplicationDataContainer____struct_Windows_Foundation_Collections_Internal_DefaultLifetimeTraits_struct_HSTRING_________KeyTraits { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Foundation_Collections_Internal_HashMap_struct_HSTRING_____class_Windows_Storage_ApplicationDataContainer____struct_Windows_Foundation_Collections_Internal_DefaultHash_struct_HSTRING______struct_Windows_Foundation_Collections_Internal_DefaultEqualityPredicate_struct_HSTRING______struct_Windows_Foundation_Collections_Internal_DefaultLifetimeTraits_struct_HSTRING______struct_Windows_Foundation_Collections_Internal_DefaultLifetimeTraits_class_Windows_Storage_ApplicationDataContainer_____struct_Windows_Foundation_Collections_Internal_DefaultHashMapOptions_struct_HSTRING_____class_Windows_Storage_ApplicationDataContainer____struct_Windows_Foundation_Collections_Internal_DefaultLifetimeTraits_struct_HSTRING_________View { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Foundation_Collections_Internal_HashMap_struct_HSTRING_____class_Windows__Storage__ApplicationDataContainer____struct_Windows__Foundation__Collections__Internal__DefaultHash_struct_HSTRING______struct_Windows__Foundation__Collections__Internal__DefaultEqualityPredicate_struct_HSTRING______struct_Windows__Foundation__Collections__Internal__DefaultLifetimeTraits_struct_HSTRING______struct_Windows__Foundation__Collections__Internal__DefaultLifetimeTraits_class_Windows__Storage__ApplicationDataContainer_____struct_Windows__Foundation__Collections__Internal__DefaultHashMapOptions_struct_HSTRING_____class_Windows__Storage__ApplicationDataContainer____struct_Windows__Foundation__Collections__Internal__DefaultLifetimeTraits_struct_HSTRING { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Foundation_Collections_Internal_HashMap_struct_HSTRING_____struct_IInspectable____struct_Windows_Foundation_Collections_Internal_DefaultHash_struct_HSTRING______struct_Windows_Foundation_Collections_Internal_DefaultEqualityPredicate_struct_HSTRING______struct_Windows_Foundation_Collections_Internal_DefaultLifetimeTraits_struct_HSTRING______struct_Windows_Foundation_Collections_Internal_DefaultLifetimeTraits_struct_IInspectable_____struct_Windows_Foundation_Collections_Internal_HashMapOptions_struct_HSTRING_____struct_IInspectable____struct_Windows_Foundation_Collections_Internal_DefaultLifetimeTraits_struct_HSTRING______1__0__0____Iterator { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Foundation_Collections_Internal_HashMap_struct_HSTRING_____struct_IInspectable____struct_Windows_Foundation_Collections_Internal_DefaultHash_struct_HSTRING______struct_Windows_Foundation_Collections_Internal_DefaultEqualityPredicate_struct_HSTRING______struct_Windows_Foundation_Collections_Internal_DefaultLifetimeTraits_struct_HSTRING______struct_Windows_Foundation_Collections_Internal_DefaultLifetimeTraits_struct_IInspectable_____struct_Windows_Foundation_Collections_Internal_HashMapOptions_struct_HSTRING_____struct_IInspectable____struct_Windows_Foundation_Collections_Internal_DefaultLifetimeTraits_struct_HSTRING______1__0__0____View { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Foundation_Collections_Internal_HashMap_struct_HSTRING_____struct_IInspectable____struct_Windows__Foundation__Collections__Internal__DefaultHash_struct_HSTRING______struct_Windows__Foundation__Collections__Internal__DefaultEqualityPredicate_struct_HSTRING______struct_Windows__Foundation__Collections__Internal__DefaultLifetimeTraits_struct_HSTRING______struct_Windows__Foundation__Collections__Internal__DefaultLifetimeTraits_struct_IInspectable_____struct_Windows__Foundation__Collections__Internal__HashMapOptions_struct_HSTRING_____struct_IInspectable____struct_Windows__Foundation__Collections__Internal__DefaultLifetimeTraits_struct_HSTRING______1__0__0 { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Foundation_Collections_Internal_MapChangedEventArgs_struct_HSTRING_____struct_Windows__Foundation__Collections__Internal__DefaultLifetimeTraits_struct_HSTRING { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Foundation_Collections_Internal_NaiveSplitView_struct_HSTRING_____class_Windows_Storage_ApplicationDataContainer____struct_Windows_Foundation_Collections_Internal_DefaultEqualityPredicate_struct_HSTRING______struct_Windows_Foundation_Collections_Internal_DefaultLifetimeTraits_struct_HSTRING______struct_Windows_Foundation_Collections_Internal_DefaultLifetimeTraits_class_Windows_Storage_ApplicationDataContainer_____struct_Windows_Foundation_Collections_Internal_DefaultHashMapOptions_struct_HSTRING_____class_Windows_Storage_ApplicationDataContainer____struct_Windows_Foundation_Collections_Internal_DefaultLifetimeTraits_struct_HSTRING_________Chunk { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Foundation_Collections_Internal_NaiveSplitView_struct_HSTRING_____class_Windows_Storage_ApplicationDataContainer____struct_Windows_Foundation_Collections_Internal_DefaultEqualityPredicate_struct_HSTRING______struct_Windows_Foundation_Collections_Internal_DefaultLifetimeTraits_struct_HSTRING______struct_Windows_Foundation_Collections_Internal_DefaultLifetimeTraits_class_Windows_Storage_ApplicationDataContainer_____struct_Windows_Foundation_Collections_Internal_DefaultHashMapOptions_struct_HSTRING_____class_Windows_Storage_ApplicationDataContainer____struct_Windows_Foundation_Collections_Internal_DefaultLifetimeTraits_struct_HSTRING_________ChunkElementIterator { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Foundation_Collections_Internal_NaiveSplitView_struct_HSTRING_____class_Windows_Storage_ApplicationDataContainer____struct_Windows_Foundation_Collections_Internal_DefaultEqualityPredicate_struct_HSTRING______struct_Windows_Foundation_Collections_Internal_DefaultLifetimeTraits_struct_HSTRING______struct_Windows_Foundation_Collections_Internal_DefaultLifetimeTraits_class_Windows_Storage_ApplicationDataContainer_____struct_Windows_Foundation_Collections_Internal_DefaultHashMapOptions_struct_HSTRING_____class_Windows_Storage_ApplicationDataContainer____struct_Windows_Foundation_Collections_Internal_DefaultLifetimeTraits_struct_HSTRING_________ChunkView { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Foundation_Collections_Internal_NaiveSplitView_struct_HSTRING_____class_Windows_Storage_ApplicationDataContainer____struct_Windows_Foundation_Collections_Internal_DefaultEqualityPredicate_struct_HSTRING______struct_Windows_Foundation_Collections_Internal_DefaultLifetimeTraits_struct_HSTRING______struct_Windows_Foundation_Collections_Internal_DefaultLifetimeTraits_class_Windows_Storage_ApplicationDataContainer_____struct_Windows_Foundation_Collections_Internal_DefaultHashMapOptions_struct_HSTRING_____class_Windows_Storage_ApplicationDataContainer____struct_Windows_Foundation_Collections_Internal_DefaultLifetimeTraits_struct_HSTRING_________SplitIterator { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Foundation_Collections_Internal_NaiveSplitView_struct_HSTRING_____class_Windows__Storage__ApplicationDataContainer____struct_Windows__Foundation__Collections__Internal__DefaultEqualityPredicate_struct_HSTRING______struct_Windows__Foundation__Collections__Internal__DefaultLifetimeTraits_struct_HSTRING______struct_Windows__Foundation__Collections__Internal__DefaultLifetimeTraits_class_Windows__Storage__ApplicationDataContainer_____struct_Windows__Foundation__Collections__Internal__DefaultHashMapOptions_struct_HSTRING_____class_Windows__Storage__ApplicationDataContainer____struct_Windows__Foundation__Collections__Internal__DefaultLifetimeTraits_struct_HSTRING { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Foundation_Collections_Internal_NaiveSplitView_struct_HSTRING_____struct_IInspectable____struct_Windows_Foundation_Collections_Internal_DefaultEqualityPredicate_struct_HSTRING______struct_Windows_Foundation_Collections_Internal_DefaultLifetimeTraits_struct_HSTRING______struct_Windows_Foundation_Collections_Internal_DefaultLifetimeTraits_struct_IInspectable_____struct_Windows_Foundation_Collections_Internal_HashMapOptions_struct_HSTRING_____struct_IInspectable____struct_Windows_Foundation_Collections_Internal_DefaultLifetimeTraits_struct_HSTRING______1__0__0____Chunk { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Foundation_Collections_Internal_NaiveSplitView_struct_HSTRING_____struct_IInspectable____struct_Windows_Foundation_Collections_Internal_DefaultEqualityPredicate_struct_HSTRING______struct_Windows_Foundation_Collections_Internal_DefaultLifetimeTraits_struct_HSTRING______struct_Windows_Foundation_Collections_Internal_DefaultLifetimeTraits_struct_IInspectable_____struct_Windows_Foundation_Collections_Internal_HashMapOptions_struct_HSTRING_____struct_IInspectable____struct_Windows_Foundation_Collections_Internal_DefaultLifetimeTraits_struct_HSTRING______1__0__0____ChunkElementIterator { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Foundation_Collections_Internal_NaiveSplitView_struct_HSTRING_____struct_IInspectable____struct_Windows_Foundation_Collections_Internal_DefaultEqualityPredicate_struct_HSTRING______struct_Windows_Foundation_Collections_Internal_DefaultLifetimeTraits_struct_HSTRING______struct_Windows_Foundation_Collections_Internal_DefaultLifetimeTraits_struct_IInspectable_____struct_Windows_Foundation_Collections_Internal_HashMapOptions_struct_HSTRING_____struct_IInspectable____struct_Windows_Foundation_Collections_Internal_DefaultLifetimeTraits_struct_HSTRING______1__0__0____ChunkView { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Foundation_Collections_Internal_NaiveSplitView_struct_HSTRING_____struct_IInspectable____struct_Windows_Foundation_Collections_Internal_DefaultEqualityPredicate_struct_HSTRING______struct_Windows_Foundation_Collections_Internal_DefaultLifetimeTraits_struct_HSTRING______struct_Windows_Foundation_Collections_Internal_DefaultLifetimeTraits_struct_IInspectable_____struct_Windows_Foundation_Collections_Internal_HashMapOptions_struct_HSTRING_____struct_IInspectable____struct_Windows_Foundation_Collections_Internal_DefaultLifetimeTraits_struct_HSTRING______1__0__0____SplitIterator { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Foundation_Collections_Internal_NaiveSplitView_struct_HSTRING_____struct_IInspectable____struct_Windows__Foundation__Collections__Internal__DefaultEqualityPredicate_struct_HSTRING______struct_Windows__Foundation__Collections__Internal__DefaultLifetimeTraits_struct_HSTRING______struct_Windows__Foundation__Collections__Internal__DefaultLifetimeTraits_struct_IInspectable_____struct_Windows__Foundation__Collections__Internal__HashMapOptions_struct_HSTRING_____struct_IInspectable____struct_Windows__Foundation__Collections__Internal__DefaultLifetimeTraits_struct_HSTRING______1__0__0 { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Foundation_Collections_Internal_SimpleKeyValuePair_struct_HSTRING_____class_Windows__Storage__ApplicationDataContainer____struct_Windows__Foundation__Collections__Internal__DefaultLifetimeTraits_struct_HSTRING______struct_Windows__Foundation__Collections__Internal__DefaultLifetimeTraits_class_Windows__Storage__ApplicationDataContainer_____0 { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Foundation_Collections_Internal_SimpleKeyValuePair_struct_HSTRING_____struct_IInspectable____struct_Windows__Foundation__Collections__Internal__DefaultLifetimeTraits_struct_HSTRING______struct_Windows__Foundation__Collections__Internal__DefaultLifetimeTraits_struct_IInspectable_____0 { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Foundation_IAsyncOperation_class_Windows__Storage__ApplicationData { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Foundation_IAsyncOperation_impl_struct_Windows__Foundation__Internal__AggregateType_class_Windows__Storage__ApplicationData____struct_Windows__Storage__IApplicationData { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Internal_AsyncCallbackBase_class_Windows__Internal__CMarshaledInterfaceResult_struct_Windows__Storage__IApplicationData { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Internal_CMarshaledInterfaceResult_struct_Windows__Storage__IApplicationData { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Internal_ComTaskPoolHandler { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Internal_ComTaskPool_CTaskWrapper_class__lambda_c2fd7731c5ae0d37e65ea73be67c0f1b { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Internal_Details { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Internal_Details_Git { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Internal_Details_GitInvokeHelper_struct_Windows__Foundation__Collections__MapChangedEventHandler_struct_HSTRING_____struct_IInspectable_____class_Windows__Internal__GitPtr__2 { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Internal_Details_GitInvokeHelper_struct_Windows__Foundation__ITypedEventHandler_class_Windows__Storage__ApplicationData____struct_IInspectable_____class_Windows__Internal__GitPtr__2 { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Internal_GitEventSource_struct_Windows__Foundation__Collections__MapChangedEventHandler_struct_HSTRING_____struct_IInspectable_____struct_Microsoft__WRL__InvokeModeOptions__2 { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Internal_GitEventSource_struct_Windows__Foundation__ITypedEventHandler_class_Windows__Storage__ApplicationData____struct_IInspectable_____struct_Microsoft__WRL__InvokeModeOptions__2 { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Internal_GitPtr { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Internal_GitPtrImpl_class_Windows__Internal__GitPtr { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Internal_GitPtrSupportsAgile_struct_Windows__Foundation__IAsyncOperationCompletedHandler_class_Windows__Storage__ApplicationData { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Internal_GitPtrSupportsAgile_struct_Windows__Internal__INilDelegate { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Internal_StaticLifetimeStore { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Internal_String { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Internal_StringReference { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Management_Core_ApplicationDataManagerFactoryServer { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Management_Core_ApplicationDataManagerServer { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Storage_ApplicationDataCompositeValueServer { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Storage_ApplicationDataCompositeValueServer_Iterator { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Storage_ApplicationDataContainerServer { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Storage_ApplicationDataContainerSettingsServer { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Storage_ApplicationDataFactoryServer { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Storage_ApplicationDataServer { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Storage_RestrictedApplicationDataServer { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Storage_SetVersionDeferral { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Storage_SetVersionRequest { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Storage_StateABIHelpers { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Storage_StateABIHelpers_FixedWidthArrayDeserializer_1026 { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Storage_StateABIHelpers_FixedWidthArrayDeserializer_1027 { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Storage_StateABIHelpers_FixedWidthArrayDeserializer_1028 { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Storage_StateABIHelpers_FixedWidthArrayDeserializer_1029 { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Storage_StateABIHelpers_FixedWidthArrayDeserializer_1030 { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Storage_StateABIHelpers_FixedWidthArrayDeserializer_1031 { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Storage_StateABIHelpers_FixedWidthArrayDeserializer_1032 { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Storage_StateABIHelpers_FixedWidthArrayDeserializer_1033 { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Storage_StateABIHelpers_FixedWidthArrayDeserializer_1034 { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Storage_StateABIHelpers_FixedWidthArrayDeserializer_1038 { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Storage_StateABIHelpers_FixedWidthArrayDeserializer_1039 { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Storage_StateABIHelpers_FixedWidthArrayDeserializer_1040 { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Storage_StateABIHelpers_FixedWidthArrayDeserializer_1041 { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Storage_StateABIHelpers_FixedWidthArrayDeserializer_1042 { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Storage_StateABIHelpers_FixedWidthArrayDeserializer_1043 { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Storage_StateABIHelpers_FixedWidthArraySerializer_1025 { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Storage_StateABIHelpers_FixedWidthArraySerializer_1026 { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Storage_StateABIHelpers_FixedWidthArraySerializer_1027 { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Storage_StateABIHelpers_FixedWidthArraySerializer_1028 { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Storage_StateABIHelpers_FixedWidthArraySerializer_1029 { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Storage_StateABIHelpers_FixedWidthArraySerializer_1030 { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Storage_StateABIHelpers_FixedWidthArraySerializer_1031 { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Storage_StateABIHelpers_FixedWidthArraySerializer_1032 { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Storage_StateABIHelpers_FixedWidthArraySerializer_1033 { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Storage_StateABIHelpers_FixedWidthArraySerializer_1034 { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Storage_StateABIHelpers_FixedWidthArraySerializer_1035 { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Storage_StateABIHelpers_FixedWidthArraySerializer_1038 { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Storage_StateABIHelpers_FixedWidthArraySerializer_1039 { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Storage_StateABIHelpers_FixedWidthArraySerializer_1040 { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Storage_StateABIHelpers_FixedWidthArraySerializer_1041 { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Storage_StateABIHelpers_FixedWidthArraySerializer_1042 { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Storage_StateABIHelpers_FixedWidthArraySerializer_1043 { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Storage_StateABIHelpers_FixedWidthSingleValueDeserializer_1 { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Storage_StateABIHelpers_FixedWidthSingleValueDeserializer_10 { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Storage_StateABIHelpers_FixedWidthSingleValueDeserializer_14 { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Storage_StateABIHelpers_FixedWidthSingleValueDeserializer_15 { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Storage_StateABIHelpers_FixedWidthSingleValueDeserializer_16 { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Storage_StateABIHelpers_FixedWidthSingleValueDeserializer_17 { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Storage_StateABIHelpers_FixedWidthSingleValueDeserializer_18 { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Storage_StateABIHelpers_FixedWidthSingleValueDeserializer_19 { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Storage_StateABIHelpers_FixedWidthSingleValueDeserializer_2 { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Storage_StateABIHelpers_FixedWidthSingleValueDeserializer_3 { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Storage_StateABIHelpers_FixedWidthSingleValueDeserializer_4 { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Storage_StateABIHelpers_FixedWidthSingleValueDeserializer_5 { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Storage_StateABIHelpers_FixedWidthSingleValueDeserializer_7 { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Storage_StateABIHelpers_FixedWidthSingleValueDeserializer_8 { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Storage_StateABIHelpers_FixedWidthSingleValueDeserializer_9 { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Storage_StateABIHelpers_FixedWidthSingleValueSerializer_1 { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Storage_StateABIHelpers_FixedWidthSingleValueSerializer_10 { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Storage_StateABIHelpers_FixedWidthSingleValueSerializer_11 { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Storage_StateABIHelpers_FixedWidthSingleValueSerializer_14 { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Storage_StateABIHelpers_FixedWidthSingleValueSerializer_15 { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Storage_StateABIHelpers_FixedWidthSingleValueSerializer_16 { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Storage_StateABIHelpers_FixedWidthSingleValueSerializer_17 { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Storage_StateABIHelpers_FixedWidthSingleValueSerializer_18 { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Storage_StateABIHelpers_FixedWidthSingleValueSerializer_19 { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Storage_StateABIHelpers_FixedWidthSingleValueSerializer_2 { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Storage_StateABIHelpers_FixedWidthSingleValueSerializer_3 { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Storage_StateABIHelpers_FixedWidthSingleValueSerializer_4 { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Storage_StateABIHelpers_FixedWidthSingleValueSerializer_5 { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Storage_StateABIHelpers_FixedWidthSingleValueSerializer_6 { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Storage_StateABIHelpers_FixedWidthSingleValueSerializer_7 { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Storage_StateABIHelpers_FixedWidthSingleValueSerializer_8 { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Storage_StateABIHelpers_FixedWidthSingleValueSerializer_9 { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Storage_StateABIHelpers_Logging { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Storage_StateABIHelpers_PropertyValueTraits_1 { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Storage_StateABIHelpers_PropertyValueTraits_10 { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Storage_StateABIHelpers_PropertyValueTraits_1025 { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Storage_StateABIHelpers_PropertyValueTraits_1026 { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Storage_StateABIHelpers_PropertyValueTraits_1027 { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Storage_StateABIHelpers_PropertyValueTraits_1028 { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Storage_StateABIHelpers_PropertyValueTraits_1029 { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Storage_StateABIHelpers_PropertyValueTraits_1030 { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Storage_StateABIHelpers_PropertyValueTraits_1031 { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Storage_StateABIHelpers_PropertyValueTraits_1032 { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Storage_StateABIHelpers_PropertyValueTraits_1033 { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Storage_StateABIHelpers_PropertyValueTraits_1034 { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Storage_StateABIHelpers_PropertyValueTraits_1035 { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Storage_StateABIHelpers_PropertyValueTraits_1036 { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Storage_StateABIHelpers_PropertyValueTraits_1038 { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Storage_StateABIHelpers_PropertyValueTraits_1039 { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Storage_StateABIHelpers_PropertyValueTraits_1040 { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Storage_StateABIHelpers_PropertyValueTraits_1041 { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Storage_StateABIHelpers_PropertyValueTraits_1042 { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Storage_StateABIHelpers_PropertyValueTraits_1043 { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Storage_StateABIHelpers_PropertyValueTraits_11 { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Storage_StateABIHelpers_PropertyValueTraits_12 { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Storage_StateABIHelpers_PropertyValueTraits_14 { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Storage_StateABIHelpers_PropertyValueTraits_15 { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Storage_StateABIHelpers_PropertyValueTraits_16 { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Storage_StateABIHelpers_PropertyValueTraits_17 { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Storage_StateABIHelpers_PropertyValueTraits_18 { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Storage_StateABIHelpers_PropertyValueTraits_19 { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Storage_StateABIHelpers_PropertyValueTraits_2 { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Storage_StateABIHelpers_PropertyValueTraits_3 { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Storage_StateABIHelpers_PropertyValueTraits_4 { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Storage_StateABIHelpers_PropertyValueTraits_5 { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Storage_StateABIHelpers_PropertyValueTraits_6 { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Storage_StateABIHelpers_PropertyValueTraits_7 { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Storage_StateABIHelpers_PropertyValueTraits_8 { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Storage_StateABIHelpers_PropertyValueTraits_9 { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Storage_StateABIHelpers_SettingPropertyToApiSetValueConverter { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Storage_StateABIHelpers_VariableWidthArrayDeserializer_1036 { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Storage_StateABIHelpers_VariableWidthArraySerializer_1036 { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Storage_StateABIImplementation_ClearOperation { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Storage_StateABIImplementation_DataChangedSignaler_struct_Windows__Foundation__ITypedEventHandler_class_Windows__Storage__ApplicationData____struct_IInspectable_____struct_Windows__Storage__IApplicationData { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Storage_StateABIImplementation_GetForUserOperation { _opaque: [u8; 0] }

#[repr(C)]
pub struct Windows_Storage_StateABIImplementation_SetVersionOperation { _opaque: [u8; 0] }

#[repr(C)]
pub struct XWinRT_ComLock { _opaque: [u8; 0] }

#[repr(C)]
pub struct XWinRT_FakeStl { _opaque: [u8; 0] }

#[repr(C)]
pub struct XWinRT_InterfaceLifetimeTraits { _opaque: [u8; 0] }

#[repr(C)]
pub struct XWinRT_SecureVersionTag_Tag { _opaque: [u8; 0] }

#[repr(C)]
pub struct XWinRT_SecureVersionTag_TagManager { _opaque: [u8; 0] }

#[repr(C)]
pub struct XWinRT_SerializingLockPolicy { _opaque: [u8; 0] }

#[repr(C)]
pub struct XWinRT_StringEquals { _opaque: [u8; 0] }

#[repr(C)]
pub struct XWinRT_XHashMap_struct_HSTRING_____struct_IInspectable____struct_Windows__Foundation__Collections__Internal__HashMap_struct_HSTRING_____struct_IInspectable____struct_Windows__Foundation__Collections__Internal__DefaultHash_struct_HSTRING______struct_Windows__Foundation__Collections__Internal__DefaultEqualityPredicate_struct_HSTRING______struct_Windows__Foundation__Collections__Internal__DefaultLifetimeTraits_struct_HSTRING______struct_Windows__Foundation__Collections__Internal__DefaultLifetimeTraits_struct_IInspectable_____struct_Windows__Foundation__Collections__Internal__HashMapOptions_struct_HSTRING_____struct_IInspectable____struct_Windows__Foundation__Collections__Internal__DefaultLifetimeTraits_struct_HSTRING______1__0__0_____KeyTraits__class_XWinRT__CElementTraits_struct_IInspectable { _opaque: [u8; 0] }

#[repr(C)]
pub struct XWinRT_XHashMap_struct_HSTRING_____struct_Windows__Storage__IApplicationDataContainer____struct_Windows__Foundation__Collections__Internal__HashMap_struct_HSTRING_____class_Windows__Storage__ApplicationDataContainer____struct_Windows__Foundation__Collections__Internal__DefaultHash_struct_HSTRING______struct_Windows__Foundation__Collections__Internal__DefaultEqualityPredicate_struct_HSTRING______struct_Windows__Foundation__Collections__Internal__DefaultLifetimeTraits_struct_HSTRING______struct_Windows__Foundation__Collections__Internal__DefaultLifetimeTraits_class_Windows__Storage__ApplicationDataContainer_____struct_Windows__Foundation__Collections__Internal__DefaultHashMapOptions_struct_HSTRING_____class_Windows__Storage__ApplicationDataContainer____struct_Windows__Foundation__Collections__Internal__DefaultLifetimeTraits_struct_HSTRING__________KeyTraits__class_XWinRT__CElementTraits_struct_Windows__Storage__IApplicationDataContainer { _opaque: [u8; 0] }

#[repr(C)]
pub struct XWinRT_detail_ReentrancyGuard_0 { _opaque: [u8; 0] }

#[repr(C)]
pub struct XWinRT_detail_ReentrancyGuard_1 { _opaque: [u8; 0] }

#[repr(C)]
pub struct lambda_0374aa0a5d1201b2358c6bce99369c58 { _opaque: [u8; 0] }

#[repr(C)]
pub struct lambda_152aa9d2a3a0648fa2fa7fcef514b376 { _opaque: [u8; 0] }

#[repr(C)]
pub struct lambda_1ad7ecfab602a777ecf020873216a663 { _opaque: [u8; 0] }

#[repr(C)]
pub struct lambda_5035b992506f4af81a770c5842624510 { _opaque: [u8; 0] }

#[repr(C)]
pub struct lambda_5f1dd388c03885d19ee806198d2ac5ef { _opaque: [u8; 0] }

#[repr(C)]
pub struct lambda_aa194dc0bf891154933407eb98fb868a { _opaque: [u8; 0] }

#[repr(C)]
pub struct lambda_d51448ba32f8ef42e59400edd4566183 { _opaque: [u8; 0] }

#[repr(C)]
pub struct lambda_fee8cea507d2413a58be13acfb66740a { _opaque: [u8; 0] }

